version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway_shareit
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: server_shareit
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=lessor
      - POSTGRES_PASSWORD=lessor
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=lessor
      - POSTGRES_PASSWORD=lessor
