version: '3.8'
services:
  gateway:
    build: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: gateway/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=later
      - POSTGRES_USER=lessor
      - POSTGRES_PASSWORD=lessor
      - DB_HOST=db
      - DB_PORT=6541

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=lessor
      - POSTGRES_PASSWORD=lessor
